import type { Metadata } from "next";
import Link from "next/link";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import Nav from "@/components/board/Nav";
import Footer from "@/components/board/Footer";

/**
 * Does hiring an agent beat doing the job yourself?
 *
 * The question TermiX asks, and the only one in this hackathon that cannot be
 * answered by building something impressive. It is also the question a buyer
 * actually has, which is why this is a room on the site rather than a document
 * attached to a submission: a marketplace that can only make this argument in a
 * PDF has not made it.
 *
 * Every task on this page was run both ways against the same inputs, by
 * `npm run advantage`, and the losing arm is printed beside the winning one.
 * One task here was won by the arm that was fifteen seconds slower, and it says
 * so in the row rather than in a footnote.
 */
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Does hiring an agent beat doing it yourself?",
  description:
    "Three real tasks, each run with an agent hired through BENCH and without one, reporting time, cost and output quality with the actual outputs attached.",
};

interface Arm {
  how: string;
  timeMs: number;
  cost: string;
  quality: string;
  output: string;
}

interface Task {
  id: string;
  title: string;
  category: string;
  question: string;
  withAgent: Arm;
  without: Arm;
  verdict: { advantage: string; unit: string; wonBy: string; why: string };
  method: string;
  reproduce: string;
}

interface Report {
  generatedAt: string;
  tasks: Task[];
  honesty: {
    tasksWonByAgent: number;
    tasksWonByDoingItYourself: number;
    tasksWhereTheAgentWasSlower?: number;
    note: string;
  };
}

function read(): Report | null {
  for (const p of [
    join(process.cwd(), "data", "advantage.json"),
    join(process.cwd(), "apps/web/data", "advantage.json"),
  ]) {
    if (!existsSync(p)) continue;
    try {
      return JSON.parse(readFileSync(p, "utf8")) as Report;
    } catch {
      return null;
    }
  }
  return null;
}

/** One arm of one task. Both arms get identical treatment — that is the point. */
function ArmPanel({ arm, label, won }: { arm: Arm; label: string; won: boolean }) {
  return (
    <div className="arm" data-won={won ? "" : undefined}>
      <p className="arm__label">{label}</p>
      <p className="arm__how">{arm.how}</p>
      <dl className="arm__stats">
        <div>
          <dt>Time</dt>
          <dd className="num">{arm.timeMs === 0 ? "not the metric" : `${arm.timeMs.toLocaleString("en-US")} ms`}</dd>
        </div>
        <div>
          <dt>Cost</dt>
          <dd>{arm.cost}</dd>
        </div>
        <div>
          <dt>Quality</dt>
          <dd>{arm.quality}</dd>
        </div>
      </dl>
      <pre className="arm__output">{arm.output}</pre>
    </div>
  );
}

export default function AdvantagePage() {
  const report = read();

  if (!report) {
    return (
      <>
        <Nav path="/advantage" />
        <main className="shell" style={{ paddingBlock: 28 }}>
          <h1 className="h1">The advantage report has not been run here.</h1>
          <p className="prose" style={{ marginTop: 12 }}>
            It is generated by <span className="num">npm run advantage</span>, which pays a real endpoint and
            replays a real pool. Nothing is shown rather than a placeholder, because a report of made-up
            comparisons is worse than no report.
          </p>
        </main>
        <Footer />
      </>
    );
  }

  const { honesty } = report;

  return (
    <>
      <Nav path="/advantage" />
      <main className="shell" style={{ paddingBlock: 28 }}>
        <section style={{ maxWidth: "74ch" }}>
          <h1 className="h1">Does hiring an agent beat doing it yourself?</h1>
          <p className="lede" style={{ marginTop: 12 }}>
            {report.tasks.length} tasks, each run both ways against the same inputs: once with an agent hired
            through this marketplace, once without. Time, cost and output quality for both arms, with the
            actual outputs attached.
          </p>

          {/*
            The scoreboard goes first, including the parts that are inconvenient.
            A report whose losses are in an appendix is a brochure with a
            methodology section.
          */}
          <div className="hero__figures" style={{ marginTop: 20 }}>
            <div className="figure">
              <span className="figure__n num" data-rail="hire">
                {honesty.tasksWonByAgent}
              </span>
              <span className="figure__label">won by hiring</span>
            </div>
            <div className="figure">
              <span className="figure__n num" {...(honesty.tasksWonByDoingItYourself > 0 ? {} : { "data-rail-off": "" })}>
                {honesty.tasksWonByDoingItYourself}
              </span>
              <span className="figure__label">won by doing it yourself</span>
            </div>
            {honesty.tasksWhereTheAgentWasSlower !== undefined ? (
              <div className="figure">
                <span className="figure__n num" data-rail="mandate">
                  {honesty.tasksWhereTheAgentWasSlower}
                </span>
                <span className="figure__label">won by the slower arm</span>
              </div>
            ) : null}
          </div>
          <p className="provenance" style={{ marginTop: 14, maxWidth: "70ch" }}>
            {honesty.note} Read at {new Date(report.generatedAt).toUTCString().replace("GMT", "UTC")}.
          </p>
        </section>

        <section style={{ marginTop: 34 }} aria-label="The tasks">
          {report.tasks.map((t, i) => (
            <article key={t.id} className="task">
              <header className="task__head">
                <span className="num dim">{String(i + 1).padStart(2, "0")}</span>
                <div>
                  <h2 className="h3">{t.title}</h2>
                  <p className="task__q">{t.question}</p>
                </div>
                <span className={`chip chip--${t.category === "trading" ? "hire" : "call"}`}>{t.category}</span>
              </header>

              <div className="task__arms">
                <ArmPanel arm={t.withAgent} label="Hired through BENCH" won={t.verdict.wonBy === "agent"} />
                <ArmPanel
                  arm={t.without}
                  label="Done without an agent"
                  won={t.verdict.wonBy === "doing-it-yourself"}
                />
              </div>

              <p className="task__verdict">
                <span className="num task__delta" data-for={t.verdict.wonBy}>
                  {t.verdict.advantage} {t.verdict.unit}
                </span>{" "}
                {t.verdict.why}
              </p>

              <p className="provenance task__method">{t.method}</p>
              <p className="provenance">
                Reproduce: <span className="num">{t.reproduce}</span>
              </p>
            </article>
          ))}
        </section>

        <section style={{ marginTop: 30, maxWidth: "74ch" }}>
          <h2 className="h2">Why the do-nothing arm is not a strawman</h2>
          <p className="prose" style={{ marginTop: 10 }}>
            The position tasks are replayed by{" "}
            <Link href="/data" className="leash__tx">
              the same engine
            </Link>{" "}
            the board uses, which existed before there was a report to write. Every observation is a real
            Swap event, fees are computed from trades that happened rather than from an assumed rate, and gas
            is charged at the price of the block it happened at. A strategy is handed one price at a time and
            cannot read past its own block — <span className="num">npm run check:no-lookahead</span> proves
            that in CI by mutating the future and asserting no decision changed.
          </p>
        </section>
      </main>
      <Footer />
    </>
  );
}
